name:                generate-all-tests
version:             0.1.0.0
github:              "srghma/generate-all-tests"
license:             BSD3
author:              "srghma"
maintainer:          "srghma@gmail.com"
copyright:           "2019 srghma"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/srghma/generate-all-tests#readme>

dependencies:
- base >= 4.7 && < 5
- turtle
- protolude
- directory
- filepath
- text
- foldl
- directory-tree
- cases

library:
  source-dirs: src

executables:
  generate-all-tests-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generate-all-tests

tests:
  generate-all-tests-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generate-all-tests
