resolver: lts-14.18

packages:
- .

extra-deps:
- github: srghma/cases
  commit: a579b01d589f8e533d2978fa4f9ded6a83e281b4

system-ghc: true # nix: enable assumes this option anyway

nix:
  enable: true
  pure: false
  shell-file: stack-shell.nix
  add-gc-roots: false
